--CREATE DATABSE--

CREATE DATABASE DAV_SCHOOL;

--USE DATABASE--

USE DAV_SCHOOL;

--CREATE TABLE--

CREATE TABLE STUDENT_DETAIL
(ROLL_NUMBER INT,
ROLL_CODE VARCHAR(20),
NAME VARCHAR(20),
CLASS INT,
ADDRESSS VARCHAR(30),
CONTACT_NUMBER NVARCHAR(10),
PARENTS_NAME VARCHAR (20),
HOUSE VARCHAR(20),
TOTAL_MARKS INT,
MARK_OBTAIN INT,
PERCENTAGE FLOAT)

--SELECT--

SELECT * FROM STUDENT_DETAIL;

--INSERT VALUE INTO TABLE--
INSERT INTO STUDENT_DETAIL VALUES(1,'JH24','ADITYA GOYAL',12,'UP',9165847845,'AJAY KUMAR','BLACK',500,400,80);
INSERT INTO STUDENT_DETAIL VALUES(2,'JH25','ANUJ TIWARI',11,'MP',8165847845,'PRADEEP KUMAR','BLACK',500,250,50);
INSERT INTO STUDENT_DETAIL VALUES(3,'JH36','MEGHA SINHA',10,'JH',8765847845,'MAHESH KUMAR','WHITE',600,300,50);
INSERT INTO STUDENT_DETAIL VALUES(4,'JH26','NEHA SINHA',11,'HP',7265847845,'MAHESH PRASAD','WHITE',600,400,66.66);
INSERT INTO STUDENT_DETAIL VALUES(5,'JH27','PANKAJ AGARWAL',12,'WB',9167547845,'SAPAN AGARWAL','BLACK',500,300,60);
INSERT INTO STUDENT_DETAIL VALUES(6,'JH28','KUNAL SINHA',11,'GJ',917847845,'MAHESH SINHA','WHITE',800,400,50);
INSERT INTO STUDENT_DETAIL VALUES(7,'JH29','RUPESH KUMAR',10,'BR',9165847887,'SANJAY KUMAR','BLACK',500,450,90);
INSERT INTO STUDENT_DETAIL VALUES(8,'JH30','GOURAV SETH',12,'JK',9168847845,'AJAY PRASAD','WHITE',700,400,57.14);
INSERT INTO STUDENT_DETAIL VALUES(9,'JH33','ANKUR KUMAR',10,'TN',6665847845,'VIJAY GANGULY','BLACK',900,450,50);
INSERT INTO STUDENT_DETAIL VALUES(10,'JH31','TAPAS KUMAR',12,'KR',9111847845,'RAM KUMAR','WHITE',1000,800,80);

--SELECT TABLE--
SELECT * FROM STUDENT_DETAIL;

--CREATE NEW TABLE TEACHER DETAIL--

CREATE TABLE TEACHER_DETAIL(
JOB_ID VARCHAR(20),
NAME VARCHAR(20),
SUBJECT VARCHAR(10),
SALARY INT,
QUALIFICATION VARCHAR (30),
ADRESS VARCHAR (20),
CONTACT_NUMBER NVARCHAR(10),
HOUSE VARCHAR(20));

--INSERT VALUE INTO NEW TABLE--

INSERT INTO TEACHER_DETAIL VALUES('D15','MOHIT KUMAR','MATH',20000,'B.SC','UP',6547893254,'BLACK');
INSERT INTO TEACHER_DETAIL VALUES('D16','SOHAM GHOSH','COMPUTER',50000,'B.TECH','KR',8747893254,'WHITE');
INSERT INTO TEACHER_DETAIL VALUES('D17','SAYAK GHOSH','SQL',80000,'B.COM','TN',6547893245,'BLACK');
INSERT INTO TEACHER_DETAIL VALUES('D18','RAJ KUMAR','TABLEAU',28000,'B.A','BR',6547323254,'WHITE');
INSERT INTO TEACHER_DETAIL VALUES('D19','SANJAY SEXENA','POWER BI',30000,'MBA','GJ',6547893324,'BLACK');
INSERT INTO TEACHER_DETAIL VALUES('D20','PRAKASH OJHA','EXCEL',60000,'BBA','DL',6896593254,'BLACK');
INSERT INTO TEACHER_DETAIL VALUES('D21','SIMARAN TIGGA','PYTHON',35000,'B.SC','HP',9547893254,'WHITE');
INSERT INTO TEACHER_DETAIL VALUES('D22','SAPNA KUMARI','R',65000,'BA','BR',6547993254,'BLACK');
INSERT INTO TEACHER_DETAIL VALUES('D23','SAPAN DUBEY','AZURE',40000,'B.COM','UK',6947893254,'WHITE');
INSERT INTO TEACHER_DETAIL VALUES('D24','RAJDEEP SODHI','MS OFFICE',10000,'B.A','JH',6547893954,'BLACK');

--SELECT SECOND TABLE TEACHER DETAIL--

SELECT * FROM TEACHER_DETAIL;

--WHERE CLAUSE---

SELECT * FROM TEACHER_DETAIL WHERE SALARY = 65000;
SELECT * FROM TEACHER_DETAIL WHERE SALARY > 40000;
SELECT * FROM STUDENT_DETAIL WHERE ROLL_CODE ='jh25';
SELECT ROLL_NUMBER,CLASS,TOTAL_MARKS FROM STUDENT_DETAIL WHERE NAME = 'MEGHA SINHA';

-- SELECT--
SELECT NAME FROM STUDENT_DETAIL;
SELECT NAME,ADDRESSS,PERCENTAGE FROM STUDENT_DETAIL;
SELECT NAME FROM TEACHER_DETAIL;
SELECT NAME,ADRESS,CONTACT_NUMBER FROM TEACHER_DETAIL;
SELECT NAME FROM STUDENT_DETAIL WHERE CLASS=11;

---UPDATE---

UPDATE TEACHER_DETAIL SET SALARY = SALARY+1000;
UPDATE TEACHER_DETAIL SET QUALIFICATION = 'MBA' WHERE JOB_ID='D15';
UPDATE STUDENT_DETAIL SET NAME='MADHUMITA SINHA',PARENTS_NAME= 'MAHESH KUMAR SINHA' WHERE ROLL_CODE = 'JH36';

---ORDER BY---

SELECT * FROM TEACHER_DETAIL ORDER BY NAME ASC;
SELECT * FROM TEACHER_DETAIL ORDER BY NAME DESC;
SELECT * FROM STUDENT_DETAIL ORDER BY PERCENTAGE ASC;
SELECT * FROM STUDENT_DETAIL ORDER BY CLASS DESC;

---AGGREGATE FUNCTION----

SELECT SUM (SALARY) FROM TEACHER_DETAIL;
SELECT MAX(SALARY) FROM TEACHER_DETAIL;
SELECT MIN (SALARY) FROM TEACHER_DETAIL;
SELECT AVG (SALARY) FROM TEACHER_DETAIL;
SELECT COUNT (SALARY) FROM TEACHER_DETAIL;

---NOT--

SELECT * FROM TEACHER_DETAIL WHERE NOT SALARY=40000;
SELECT * FROM STUDENT_DETAIL WHERE NOT PERCENTAGE = 80;

---BETWEEN--

SELECT * FROM TEACHER_DETAIL WHERE SALARY BETWEEN 40000 AND 80000;
SELECT * FROM STUDENT_DETAIL WHERE PERCENTAGE BETWEEN 60 AND 80;

--LIKE--

SELECT * FROM TEACHER_DETAIL WHERE NAME LIKE 'S%';
SELECT * FROM STUDENT_DETAIL WHERE NAME LIKE 'M%';
SELECT * FROM STUDENT_DETAIL WHERE NAME LIKE '%A';
SELECT * FROM STUDENT_DETAIL WHERE  NAME LIKE'%SIN%';
SELECT * FROM STUDENT_DETAIL WHERE NAME LIKE '_E%';
SELECT * FROM STUDENT_DETAIL WHERE NAME LIKE '__N%';
SELECT * FROM STUDENT_DETAIL WHERE NAME NOT LIKE 'S%'; 
SELECT * FROM STUDENT_DETAIL WHERE NAME NOT LIKE '%L';

--thanks--
